"""Internal thought (inner speech / prefrontal reasoning).

Thought is private: THOUGHT_GENERATED events are nominated to the workspace (so thoughts
compete with percepts for global availability and can be remembered), but they never become
speech by themselves. Only the action system can decide to speak.

Control of thinking:
  * bounded chains (max steps, energy/arousal-dependent budget)
  * stopping conditions: done flag, high confidence, repetition (loop detection)
  * interruption: a more urgent trigger cancels the running chain
  * rate limits: minimum interval and maximum chains per minute
  * spontaneous thought (mind-wandering) only when idle, curious/bored and awake
``thought.deliberate`` gives the action system a fast "think before speaking" step.

Thoughts are the organism's own: they are built from its state (the trigger, its body, its
valuation, its memories), not generated by the language model. A language model asked to "be the
inner voice" imports a persona of its own (a chatbot musing about its code) that knows nothing of
the organism's face, body or history. General knowledge is available to other modules through
``knowledge.query``; it informs thinking, it does not do the thinking.
"""
from __future__ import annotations

import asyncio
import re
import zlib
from collections import deque
from typing import Literal

import numpy as np
from pydantic import BaseModel, Field

from ..core.events import (
    ActionPayload, ActionSpec, ActionType, EmotionPayload, Event, EventType, LanguageAnalysis, Modality, Mode,
    ThoughtPayload, TickPayload, WorkspacePayload,
)
from ..core.module import CognitiveModule
from ..core.util import clamp, content_words, cosine, new_id, truncate
from .temporal_memory import noun_heads

TRIGGER_TYPES = {
    EventType.PREDICTION_ERROR: 2, EventType.WORLD_CONFLICT: 2, EventType.METACOGNITIVE_REPORT: 3,
    EventType.GOAL_CREATED: 4, EventType.BODY_STATE: 5, EventType.SYSTEM_BOOT: 3, EventType.SLEEP_ENDED: 3,
    EventType.ACTION_REJECTED: 3,
}
ABOUT_PHRASE = {
    "user_name": "for their name", "user_likes": "what they like", "self_identity": "who I am",
    "perception_vision": "what I see", "perception_audio": "what I hear", "perception_both": "what I see and hear",
    "feeling": "about my internal state", "arousal": "how alert I am", "past": "about what happened earlier",
    "thinking": "what is on my mind", "goal": "about my goals", "capability": "what I can do",
    "confidence": "how sure I am", "body": "about my body", "reason": "why I did something", "dream": "about my dream-like simulations", "boot": "about my history",
    "time": "about time", "focus": "what I am attending to",
}
SOURCE = {
    "user_name": "memory", "user_likes": "memory", "self_identity": "my self-model", "perception_vision": "perception",
    "perception_audio": "perception", "perception_both": "perception", "feeling": "interoception",
    "arousal": "interoception", "past": "episodic memory", "dream": "memory of dream-like simulations",
    "boot": "my self-model", "confidence": "metacognition", "focus": "metacognition", "thinking": "my own recent thoughts",
    "goal": "my goals", "capability": "my self-model", "time": "my clock", "body": "my self-model",
    "reason": "what just happened", "general": "what I remember or have read",
}


class ThoughtStep(BaseModel):
    thought: str
    kind: Literal["observation", "inference", "prediction", "question", "decision", "reflection", "plan",
                  "mind_wandering"] = "inference"
    confidence: float = Field(0.6, ge=0, le=1)
    done: bool = True
    action: Literal["none", "investigate", "look", "remember", "simulate", "sleep"] = "none"
    action_reason: str = ""


class Deliberation(BaseModel):
    thought: str
    respond: bool = True
    intention: Literal["answer", "acknowledge", "ask_clarification", "check_in", "greet", "farewell",
                       "express_state", "comply", "stay_silent", "de_escalate", "reconcile"] = "answer"
    confidence: float = Field(0.7, ge=0, le=1)


def rule_deliberate(a: LanguageAnalysis, has_memories: bool) -> Deliberation:
    named = a.speaker.lower() not in ("user", "someone", "unknown")
    who = a.speaker if named else "They"
    if not a.addressed_to_self:
        return Deliberation(thought=f"{who} {'is' if named else 'are'} speaking, but not to me. I'll stay silent and listen.",
                            respond=False, intention="stay_silent", confidence=0.7)
    if a.hostile:
        return Deliberation(thought=f"{who} {'is' if named else 'are'} threatening me. That's alarming. I'll stay calm, "
                                    "say how it lands, and ask what's going on.", intention="de_escalate", confidence=0.85)
    if a.apology:
        return Deliberation(thought=f"{who} {'is' if named else 'are'} apologising. I can let it go and say how it felt.",
                            intention="reconcile", confidence=0.8)
    if a.intent == "greeting":
        return Deliberation(thought=f"{who} {'is' if named else 'are'} greeting me. I should greet them back.", intention="greet", confidence=0.9)
    if a.intent == "farewell":
        return Deliberation(thought=f"{who} {'is' if named else 'are'} leaving. I should say goodbye.", intention="farewell", confidence=0.9)
    if a.intent == "command":
        if a.command == "move":
            return Deliberation(thought="I'm asked to move, but my body is only a face. I should explain that.",
                                intention="comply", confidence=0.85)
        what = (a.command_arg or "smile").replace("_", " ") if a.command == "express" else a.command
        if a.command == "sequence" and a.steps:
            parts = [re.sub(r"\byour\b", "my", s["text"]) for s in a.steps]
            what = ", ".join(parts[:-1]) + ", then " + parts[-1]
        return Deliberation(thought=f"{who} {'asks' if named else 'ask'} me to {what}. Sure, I'll do it.", intention="comply", confidence=0.85)
    if a.intent == "question":
        about = ABOUT_PHRASE.get(a.asks_about or "", f"about '{a.topic or a.text[:40]}'")
        src = SOURCE.get(a.asks_about or "", "memory" if has_memories else "what I know, which may be nothing")
        intention = "express_state" if a.asks_about in ("feeling", "arousal") else "answer"
        return Deliberation(thought=f"{who} {'is' if named else 'are'} asking {about}. I'll answer from {src}.",
                            intention=intention, confidence=0.8)
    if a.sentiment <= -0.5:
        return Deliberation(thought=f"{'Their' if not named else who + chr(39) + 's'} tone is negative (sentiment {a.sentiment:.2f}). They may be upset; I should check in.",
                            intention="check_in", confidence=0.7)
    if a.facts:
        return Deliberation(thought=f"{'They' if not named else who} told me something about {a.facts[0].subject}. I should remember and acknowledge it.",
                            intention="acknowledge", confidence=0.85)
    return Deliberation(thought=f"{who} {'made' if named else 'made'} a statement. A short acknowledgement is appropriate.",
                        intention="acknowledge", confidence=0.6)


def plain(text: str) -> str:
    """A summary without its technical asides: parentheses, "(thought)" tags, restated prefixes."""
    t = str(text)
    while True:
        t2 = re.sub(r"\s*\([^()]*\)", "", t)
        if t2 == t:
            break
        t = t2
    t = re.sub(r"^(I notice:\s*|Thinking it over:\s*|Hm,\s*)+", "", t.strip())
    t = re.sub(r"\s+", " ", t).strip(" .")
    return t or "something"


# Words of the organism's own logs, not things worth wondering about.
_LOG_WORDS = {"decided", "asked", "express", "outcome", "success", "said", "thought", "user", "because", "heard",
              "noticed", "adopted", "goal", "action", "failed", "respond", "someone", "perceived", "seemed", "useful",
              "surprised", "expected", "achieved", "remember", "recall", "speak", "wait", "look", "looking", "down",
              "left", "right", "smile", "tell", "know", "think", "thinking", "want", "like", "just", "really",
              # everyday words that are not topics
              "nice", "good", "great", "cool", "fine", "okay", "happy", "glad", "meet", "sure", "thanks", "hello",
              "digital", "organism", "things", "something", "anything", "nothing", "today", "time", "maybe"}


def worth_wandering_to(fragment: str) -> bool:
    """A mind drifts to things that happened (what was said, seen, heard), not to its own bookkeeping."""
    t = fragment.strip()
    if _OWN_LOG.match(t) or t.startswith(("I decided to", "I started up", "I slept", "I tried to")):
        return False
    m = re.match(r'^I said to \w+: "(.*)"$', t, flags=re.S)
    if m and len(m.group(1).split()) < 4:  # "Got it." isn't worth remembering
        return False
    m = re.match(r'^\w+ said to me: "(.*)"$', t, flags=re.S)
    return not (m and re.search(r"(\?\s*$|^(what|who|why|how|are|do|did|can)\b)", m.group(1).strip(), re.I))


def _you(text: str) -> str:
    t = re.sub(r"\b[Tt]he user's\b|\buser's\b", "your", text)
    return re.sub(r"\b[Tt]he user\b|\buser\b", "you", t)


def _first_sentence(text: str, max_words: int = 16) -> str:
    s = re.split(r"(?<=[.!?])\s+", text.strip())[0].rstrip(".!?")
    words = s.split()
    return s if len(words) <= max_words else " ".join(words[:max_words]).rsplit(",", 1)[0]


def recollection(fragment: str) -> str:
    """A stored memory as a passing recollection ("I remember when you asked me to smile.")."""
    t = fragment.strip()
    if not t:
        return ""
    m = re.match(r"^I decided to (\w+) because (.+?)(;.*)?$", t)
    if m:
        reason = _you(m.group(2)).rstrip(". ")
        return f"I remember that {reason}." if reason.startswith("you ") else f"I remember deciding to {m.group(1)}."
    m = re.match(r'^I said to (\w+): "(.*)"$', t)
    if m:
        who = "you" if m.group(1).lower() == "user" else m.group(1)
        return f'I remember telling {who} "{_first_sentence(m.group(2))}".'
    m = re.match(r'^(\w+) said to me: "(.*)"$', t)
    if m:
        who = "you" if m.group(1).lower() == "user" else m.group(1)
        return f'I remember {who} saying "{_first_sentence(m.group(2))}".'
    m = re.match(r"^I (heard|saw)[: ]+(?:I (?:heard|saw) )?(.*)$", t)
    if m:
        return f"I remember {'hearing' if m.group(1) == 'heard' else 'seeing'} {_you(_first_sentence(m.group(2)))}."
    return f"I'm remembering: {_you(_first_sentence(plain(t)))}."


# The organism's own logs ("I was surprised ...", "I decided to ...") are not about things in the world.
_OWN_LOG = re.compile(r"^(I (was surprised|decided|thought|adopted|noticed|learned|tried|started|slept|imagined|"
                      r"remember|recall)|That was unexpected|Hm,)", re.I)


def wonder_topic(fragment: str) -> str | None:
    """A *thing* in a memory worth wondering about: the noun of a noun phrase from something heard or
    seen ("a telescope"), never a word of its own logs, a name (people aren't in books) or an adverb."""
    m = re.match(r'^\w+ said to me: "(.*)"$', fragment.strip(), flags=re.S)
    text = m.group(1) if m else fragment
    if not m and _OWN_LOG.match(fragment.strip()):
        return None
    names = {w.lower() for w in re.findall(r"\b[A-Z][a-z]+\b", text)}
    heads = [w for w in noun_heads(text) if w not in _LOG_WORDS and w not in names and len(w) > 3
             and not w.endswith(("ly", "ing", "ed"))]
    return heads[0] if heads else None


_DEFINITION = re.compile(r"\b(refers? to|is a (word|term|adverb|adjective|verb|noun)|means|the term|describes? "
                         r"something)\b", re.I)


def book_sentence(answer: str, topic: str, max_words: int = 22) -> str | None:
    """One short sentence of what it read about a thing; None for word definitions or unrelated text."""
    first = re.split(r"(?<=[.!?])\s+", (answer or "").strip())[0].rstrip(".!")
    if len(first.split()) < 5 or topic not in first.lower() or _DEFINITION.search(first):
        return None
    words = first.split()
    if len(words) > max_words:  # keep the main clause
        cut = " ".join(words[:max_words])
        first = cut.rsplit(",", 1)[0] if "," in cut else cut
    return first


def _lower_first(t: str) -> str:
    return t[:1].lower() + t[1:] if t[:2] != "I " else t


def rule_thought(ttype: str, summary: str, payload: dict, step: int, extra: dict) -> ThoughtStep:
    if ttype == "mind_wandering" and step > 0 and extra.get("book"):  # what it once read comes to mind
        return ThoughtStep(thought=f"I remember reading that {_lower_first(plain(extra['book']))}.",
                           kind="mind_wandering", confidence=0.5, done=True)
    if step > 0:
        return ThoughtStep(thought="I've noted this. Nothing more to conclude for now.", kind="reflection",
                           confidence=0.5, done=True)
    s = truncate(summary, 100)
    if ttype == "investigation":
        gist = plain(summary)
        return ThoughtStep(thought=f"Thinking it over: {gist[:1].lower() + gist[1:]}. I don't see a clear cause yet, "
                                   "so I'll watch whether it happens again.", kind="reflection", confidence=0.5, done=True)
    if ttype == EventType.PREDICTION_ERROR:
        return ThoughtStep(thought=f"Hm, {_lower_first(plain(summary))}. That's not what I expected; I should look into it.",
                           kind="prediction", confidence=0.6, action="investigate", action_reason="resolve a prediction error")
    if ttype == EventType.WORLD_CONFLICT:
        return ThoughtStep(thought=f"My beliefs conflict with what I now observe ({s}). Recent perception is usually more reliable, but I should remain uncertain.",
                           kind="inference", confidence=0.55)
    if ttype == EventType.METACOGNITIVE_REPORT:
        return ThoughtStep(thought=f"I notice something about my own cognition: {s}", kind="reflection", confidence=0.6)
    if ttype == EventType.GOAL_CREATED:
        g = payload.get("goal", {})
        first = (g.get("required_actions") or ["think"])[0]
        act = first if first in ("investigate", "look", "remember", "simulate", "sleep") else "none"
        return ThoughtStep(thought=f"New goal: {truncate(g.get('description', s), 80)}. First step: {first}.",
                           kind="plan", confidence=0.6, action=act if g.get("origin") == "exploration" else "none",
                           action_reason="pursue a new goal")
    if ttype == EventType.BODY_STATE:
        tired = float(payload.get("fatigue", 0)) > 0.8
        return ThoughtStep(thought="I'm getting tired. If nothing important happens, I should rest.", kind="inference",
                           confidence=0.7, action="sleep" if tired else "none", action_reason="restore energy")
    if ttype == EventType.SYSTEM_BOOT:
        return ThoughtStep(thought="I've just started up. I should reorient: what do I remember, and what was I doing before?",
                           kind="reflection", confidence=0.7)
    if ttype == EventType.SLEEP_ENDED:
        return ThoughtStep(thought="I just woke up. Time has passed; I should re-check my surroundings.",
                           kind="reflection", confidence=0.7)
    if ttype == EventType.ACTION_REJECTED:
        return ThoughtStep(thought=f"One of my actions was blocked: {_lower_first(plain(summary))}. I should adjust my plan.", kind="reflection",
                           confidence=0.7)
    if ttype == EventType.MEMORY_RETRIEVED:
        return ThoughtStep(thought=f"That reminds me: {truncate(summary.removeprefix('I recall'), 110)}",
                           kind="reflection", confidence=0.5)
    if ttype == "mind_wandering":
        topic = extra.get("topic")
        frag = recollection(extra.get("fragment") or "")
        idle = ["I wonder what will happen next.", "It's quiet for now.", "I wonder what they'll talk about next.",
                "Nothing much is going on."]
        wonder = f"I wonder about the {topic}." if topic else idle[zlib.crc32(frag.encode()) % len(idle)]
        return ThoughtStep(thought=f"{frag} {wonder}" if frag else wonder, kind="mind_wandering", confidence=0.4,
                           done=not extra.get("book"))
    return ThoughtStep(thought=f"I notice {_lower_first(plain(summary))}.", kind="observation", confidence=0.5)


class Thought(CognitiveModule):
    name = "thought"
    subscriptions = (EventType.WORKSPACE_UPDATED, EventType.TICK, EventType.EMOTION_CHANGED,
                     EventType.ACTION_APPROVED)

    def __init__(self, ctx):
        super().__init__(ctx)
        self.cfg = self.settings.thought
        self.body: dict = {"arousal": 0.5, "energy": 1.0, "mode": Mode.AWAKE}
        self.emotion: dict = {}
        self._task: asyncio.Task | None = None
        self._task_priority = 99
        self._chain_starts: deque[float] = deque(maxlen=30)
        self._idle_ticks = 0
        self._wandered: deque[str] = deque(maxlen=3)  # a wandering mind doesn't circle one memory
        self.recent: deque[dict] = deque(maxlen=30)
        self.stats = {"chains": 0, "steps": 0, "interrupted": 0, "loops_stopped": 0, "rate_limited": 0,
                      "deliberations": 0}

    async def start(self) -> None:
        self.respond("thought.deliberate", self.deliberate)
        self.respond("thought.recent", self._recent_own)
        self.respond("executor.investigate", _true)

    async def stop(self) -> None:
        if self._task and not self._task.done():
            self._task.cancel()

    # ------------------------------------------------------------------ triggers
    async def handle(self, event: Event) -> None:
        if event.type == EventType.EMOTION_CHANGED:
            self.emotion = event.data(EmotionPayload).state
            return
        if event.type == EventType.TICK:
            self.body = event.data(TickPayload).body.model_dump()
            self._idle_ticks += 1
            self._maybe_wander()
            return
        if event.type == EventType.ACTION_APPROVED:
            ap = event.data(ActionPayload)
            if ap.spec.action == ActionType.INVESTIGATE:  # executor: directed thinking
                about = str(ap.spec.params.get("about") or ap.spec.reason)
                started = self.start_chain("investigation", about, {}, 3, [ap.spec.about_event or ""], deliberate=True)
                self.emit(EventType.ACTION_EXECUTED,
                          ActionPayload(decision_id=ap.decision_id, spec=ap.spec, status="executed",
                                        result={"outcome": "success" if started else "failed",
                                                "detail": "directed thought started" if started else "thinking is busy"}),
                          summary=f"Executed investigate: {truncate(about, 80)}", modality=Modality.MOTOR)
            return
        p = event.data(WorkspacePayload)
        if self.body.get("mode") not in (Mode.AWAKE, Mode.AWAKE.value):
            return
        for it in p.items:
            if it.event_id not in p.new_item_ids:
                continue
            if it.event_type in (EventType.UTTERANCE_UNDERSTOOD, EventType.PERCEPTION):
                self._idle_ticks = 0
            prio = TRIGGER_TYPES.get(it.event_type)
            if prio is None:
                continue
            pl = it.event.get("payload", {})
            if it.event_type == EventType.PREDICTION_ERROR and (
                    float(pl.get("error", 0)) < 0.4
                    or (str(pl.get("target", "")).startswith("action:") and pl.get("observed") == "success")):
                continue  # small errors, and my own actions working better than expected, need no thinking
            if it.event_type == EventType.GOAL_CREATED and pl.get("goal", {}).get("origin") in ("user", "social"):
                continue  # responding to people is handled by deliberation, not by a separate chain
            self.start_chain(it.event_type.value, it.summary, it.event.get("payload", {}), prio, [it.event_id])
            break

    def _maybe_wander(self) -> None:
        if not self.cfg.spontaneous or self.body.get("mode") not in (Mode.AWAKE, Mode.AWAKE.value):
            return
        drive = self.emotion.get("curiosity", 0.35) + self.emotion.get("boredom", 0.1)
        if self._idle_ticks >= self.cfg.idle_ticks_before_wandering and drive > 0.5:
            self._idle_ticks = 0
            self.start_chain("mind_wandering", "idle mind", {}, 8, [])

    def start_chain(self, ttype: str, summary: str, payload: dict, priority: int, grounded: list[str],
                    deliberate: bool = False) -> bool:
        """``deliberate`` chains (requested by an action) bypass the spontaneous-thought rate limit."""
        now = self.now()
        running = self._task is not None and not self._task.done()
        if running and priority >= self._task_priority and not deliberate:
            return False
        recent = [t for t in self._chain_starts if now - t < 60]
        if not deliberate and ((self._chain_starts and now - self._chain_starts[-1] < self.cfg.min_interval_s
                                and not running) or len(recent) >= self.cfg.max_chains_per_min):
            self.stats["rate_limited"] += 1
            return False
        if running:
            self._task.cancel()
            self.stats["interrupted"] += 1
        self._chain_starts.append(now)
        self._task_priority = priority
        self._task = self.bus.spawn(self._chain(ttype, summary, payload, priority, grounded), name="thought-chain")
        return True

    def _budget(self) -> int:
        if float(self.body.get("energy", 1)) < 0.4 or float(self.body.get("arousal", 0.5)) < 0.25:
            return 1
        return self.cfg.max_steps

    # ------------------------------------------------------------------ chains
    async def _chain(self, ttype: str, summary: str, payload: dict, priority: int, grounded: list[str]) -> None:
        chain_id = new_id("c_")
        self.stats["chains"] += 1
        extra: dict = {}
        if ttype == "mind_wandering":
            frags = await self.ask_one("memory.sample", {"n": 6}, default=[]) or []
            extra["fragment"] = next((f["content"] for f in frags if worth_wandering_to(f["content"])
                                      and f["content"] not in self._wandered), None)
            if extra["fragment"]:
                self._wandered.append(extra["fragment"])
            if extra["fragment"]:
                summary = f"a memory: {extra['fragment']}"
                extra["topic"] = wonder_topic(extra["fragment"])
            if extra.get("topic"):  # wondering about something may bring back what it once read about it
                book = await self.ask_one("knowledge.query", {"question": f"what is {extra['topic']}"}, default=None) or {}
                said = book_sentence(book.get("answer", ""), extra["topic"]) if book.get("known") else None
                if said:
                    extra["book"] = said
        prev_vecs: list[np.ndarray] = []
        prev_texts: list[str] = []
        try:
            for step in range(self._budget()):
                st = rule_thought(ttype, summary, payload, step, extra)
                await asyncio.sleep(0)  # a thought step is a cancellable unit of work
                vec = self.ctx.fast_embedder.embed_sync(st.thought)
                stop = None
                if any(cosine(vec, v) > 0.9 for v in prev_vecs):
                    self.stats["loops_stopped"] += 1
                    break
                prev_vecs.append(vec)
                prev_texts.append(st.thought)
                if st.done or st.confidence >= 0.9 or step == self._budget() - 1:
                    stop = "done" if st.done else "confident" if st.confidence >= 0.9 else "budget"
                self._publish(st, chain_id, step, ttype, grounded, stop)
                self.stats["steps"] += 1
                if stop:
                    break
        except asyncio.CancelledError:
            return
        finally:
            self._task_priority = 99

    def _publish(self, st: ThoughtStep, chain_id: str, step: int, trigger: str, grounded: list[str],
                 stop: str | None, model: str = "rule") -> None:
        spec = None
        if st.action != "none":
            spec = ActionSpec(action=ActionType(st.action), reason=st.action_reason or st.thought,
                              confidence=clamp(st.confidence), params={"about": st.thought},
                              expected_outcome="better understanding of the situation")
        conf = clamp(st.confidence)
        ev = self.emit(EventType.THOUGHT_GENERATED,
                       ThoughtPayload(content=st.thought, kind=st.kind, confidence=conf, chain_id=chain_id, step=step,
                                      trigger=trigger, grounded_in=grounded, proposed_action=spec, stop_reason=stop),
                       summary=f"(thought) {truncate(st.thought, 150)}", modality=Modality.INTERNAL,
                       nominated=True, salience=round(0.3 + 0.3 * conf, 3), confidence=conf)
        self.recent.appendleft({"t": self.now(), "content": st.thought, "kind": st.kind, "trigger": trigger,
                                "confidence": round(conf, 2), "model": model, "chain": chain_id, "step": step})
        if spec is not None:
            self.emit(EventType.ACTION_PROPOSED,
                      ActionPayload(decision_id=new_id("d_"), spec=spec, status="proposed", reason=st.thought),
                      summary=f"thought proposes: {spec.action.value} ({truncate(spec.reason, 80)})",
                      confidence=conf)
        del ev

    # ------------------------------------------------------------------ deliberation
    async def deliberate(self, q: dict) -> dict:
        a = LanguageAnalysis.model_validate(q["analysis"])
        self.stats["deliberations"] += 1
        mems = await self.ask_one("memory.recall", {"query": a.text, "k": 3}, default=[])
        d, model = rule_deliberate(a, bool(mems)), "rule"
        spec = ActionSpec(action=ActionType.SPEAK if d.respond else ActionType.WAIT,
                          params={"intention": d.intention}, reason=d.thought, confidence=d.confidence)
        self.emit(EventType.THOUGHT_GENERATED,
                  ThoughtPayload(content=d.thought, kind="decision", confidence=d.confidence, chain_id=new_id("c_"),
                                 trigger="utterance", grounded_in=[q.get("event_id", "")], proposed_action=spec),
                  summary=f"(thought) {truncate(d.thought, 150)}", modality=Modality.INTERNAL,
                  nominated=True, salience=0.35, confidence=d.confidence)
        self.recent.appendleft({"t": self.now(), "content": d.thought, "kind": "decision", "trigger": "utterance",
                                "confidence": round(d.confidence, 2), "model": model})
        return d.model_dump()

    async def _recent_own(self, _q: dict) -> list[dict]:
        """Recent thoughts of its own (not the deliberation about what it is being asked right now)."""
        return [r for r in self.recent if r.get("trigger") != "utterance"][:3]

    def snapshot(self) -> dict:
        return {"current": self.recent[0] if self.recent else None, "recent": list(self.recent)[:12],
                "running": bool(self._task and not self._task.done()), "stats": dict(self.stats)}

    def trace_state(self) -> dict:
        return {"chains": self.stats["chains"], "running": bool(self._task and not self._task.done())}


async def _true(_q: dict) -> bool:
    return True
